# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build beta builds and distribute to firebase"

  lane :beta do

    increment_build_number(
      xcodeproj: "JDApex Predators/JDApex Predators.xcodeproj"
    )

    build_number = get_build_number(
      xcodeproj: "JDApex Predators/JDApex Predators.xcodeproj"
    )

    puts "Current build number: #{build_number}"

    notes = changelog_from_git_commits(
      pretty: "- %s",
      merge_commit_filtering: "exclude_merges"
    )

    puts "Release notes:"
    puts notes

    ipa_path = build_app(
      scheme: "JDApex Predators",
      export_method: "development"
    )

    firebase_app_distribution(
      app: "1:213075599779:ios:c14d5936975c9f63a2ba16",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      ipa_path: ipa_path,
      release_notes: notes
    )

  end
end
